name: Deploy Mkslides

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Build slides
        run: poetry run task build

      - name: Remove reveal git folder
        run: rm -rf site/mkslides-assets/reveal-js/.git

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4